name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Configuración para el backend
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Node 20 for Backend and Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Backend Tests
        run: |
          cd backend
          mvn clean spring-boot:run & 
          echo "Waiting 5 seconds for the server to start"
          sleep 5 
          attempt_counter=0
          max_attempts=5
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080/add?num1=1&num2=1); do
            if [ ${attempt_counter} -eq ${max_attempts} ]; then
              echo "Max attempts reached"
              exit 1
            fi
            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
          done
          echo "Server ready for testing"
          npm install -g newman
          newman -v
          newman run src/test/integration/Calculator.postman_test_run.json

      # Configuración para el frontend
      - name: Set up Chrome for Frontend
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true

      - name: Run Frontend Tests
        run: |
          cd frontend/src
          python3 -m http.server 8000 &
          sleep 10 &&
          curl http://localhost:8000
          cd ..
          npm install
          cd tests
          ../node_modules/.bin/mocha *.js

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/.
