name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-22.04
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true
      - run: |
          cd frontend/src
          python3 -m http.server 8000 &
          sleep 10 &&
          curl http://localhost:8000
          cd ..
          npm install
          cd tests
          ../node_modules/.bin/mocha *.js
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/.
          
  backend:
    name: Java CI Backend
    runs-on: ubuntu-latest
    # Se ejecuta siempre en push o workflow_dispatch, y en pull_request solo si la rama base es main
    if: github.event_name != 'pull_request' || github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build with Maven and run Newman
        run: |
          cd backend
          mvn clean spring-boot:run & 
          echo "Waiting 5 seconds for the server to start"
          sleep 5 
          attempt_counter=0
          max_attempts=5
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080/add?num1=1&num2=1); do
            if [ ${attempt_counter} -eq ${max_attempts} ]; then
              echo "Max attempts reached"
              exit 1
            fi
            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
          done
          echo "Server ready for testing"
          npm install -g newman
          newman -v
          newman run src/test/integration/Calculator.postman_test_run.json
